# Generated by Django 4.1.1 on 2023-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='Asosiy mavzu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Rasm tanlang'),
        ),
        migrations.AlterField(
            model_name='article',
            name='qisqacha',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qisqa malumot'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Sarlavha'),
        ),
    ]
